name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Icons
        run: |
          npm install -g @mapbox/spritezero glob
          cd $GITHUB_WORKSPACE
          node .github/workflows/bin/icon-build.js $GITHUB_WORKSPACE

      - name: Deploy the GeoJSON to `gh-pages`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true